doorman:
    node_ip: 127.0.0.1
    node_rpc_port: 8545
    rentable_addresses:
        - "0xbac41871cf121f6c02d345af52c82c83759a2e3b"
        - "0xd089b3d41d3028951a5048ba33eadeb73fe8a0fb"
    symmetric_key_password: lokkit
    script: leFile.bat